const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://www.smartcoretech.co.uk").replace(/\/$/, "")

export const siteConfig = {
  name: "SmartCore Technologies Ltd",
  shortName: "SmartCore Technologies",
  url: siteUrl,
  title: "AI Enablement & AI Workflow Automation Services | SmartCore",
  description:
    "AI enablement leadership and AI workflow automation services for US and UK mid-market teams, covering customer service, operations, governance and handover.",
  email: "partnerships@smartcoretech.co.uk",
  privacyUpdatedAt: "2026-07-30",
  experts: {
    alexTryvailo: {
      name: "Alex Tryvailo, PhD",
      role: "AI Enablement and Automation Lead",
      bio: "AI enablement and automation specialist working across adoption strategy, workflow design, LLM evaluation, data quality, and controlled implementation.",
      url: `${siteUrl}/about/alex-tryvailo`,
      linkedin: "https://www.linkedin.com/in/trivaylo/",
      sameAs: ["https://www.linkedin.com/in/trivaylo/"],
      expertise: [
        "AI enablement",
        "AI adoption strategy",
        "AI governance",
        "AI workflow automation",
        "LLM evaluation",
        "data quality",
        "market intelligence automation",
        "workflow diagnostics",
      ],
    },
  },
  address: {
    streetAddress: "Office 15055, 182-184 High Street North",
    addressLocality: "East Ham",
    addressRegion: "London",
    postalCode: "E6 2JA",
    addressCountry: "GB",
  },
  indexing: {
    sitemapUrl: `${siteUrl}/sitemap.xml`,
    robotsUrl: `${siteUrl}/robots.txt`,
  },
  keywords: [
    "AI automation consulting",
    "AI automation services",
    "workflow automation services",
    "business process automation services",
    "AI automation consultant",
    "AI automation partner",
    "AI workflow automation",
    "AI workflow automation consulting",
    "AI workflow automation consultant",
    "operational workflow automation",
    "operational intelligence",
    "process intelligence",
    "workflow diagnostics",
    "strategic advisory",
    "systems delivery",
    "workflow automation",
    "AI-enabled systems",
    "business process automation",
    "custom AI workflow automation",
    "workflow automation consulting",
    "AI automation consulting US",
    "AI automation consulting UK",
    "AI automation consultant US",
    "AI automation consultant UK",
    "AI enablement consulting",
    "fractional AI officer",
    "fractional AI enablement lead",
    "interim head of AI",
    "AI adoption programme",
    "AI enablement programme",
    "AI governance and adoption",
    "interim AI enablement",
    "workflow diagnostic",
    "content automation",
    "reporting automation",
    "product data automation",
    "product data cleanup automation",
    "catalog image QA automation",
    "review intelligence automation",
    "customer service automation",
    "customer support automation",
    "voice of customer analytics",
    "content fact checking automation",
    "market monitoring automation",
    "internal workflow automation",
  ],
}
