const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://www.smartcoretech.co.uk").replace(/\/$/, "")

export const siteConfig = {
  name: "SmartCore Technologies Ltd",
  shortName: "SmartCore Technologies",
  url: siteUrl,
  title: "AI Automation Consulting for US and UK Teams | SmartCore",
  description:
    "SmartCore helps US and UK teams map repetitive work and build controlled AI workflows for documents, product data, monitoring, reporting, and decisions.",
  email: "partnerships@smartcoretech.co.uk",
  address: {
    streetAddress: "Office 15055, 182-184 High Street North",
    addressLocality: "East Ham",
    addressRegion: "London",
    postalCode: "E6 2JA",
    addressCountry: "GB",
  },
  keywords: [
    "AI automation consulting",
    "AI automation consultant",
    "AI automation partner",
    "AI workflow automation",
    "AI workflow automation consulting",
    "AI workflow automation consultant",
    "operational workflow automation",
    "operational intelligence",
    "process intelligence",
    "workflow diagnostics",
    "strategic advisory",
    "systems delivery",
    "workflow automation",
    "AI-enabled systems",
    "business process automation",
    "custom AI workflow automation",
    "workflow automation consulting",
    "AI automation consulting US",
    "AI automation consulting UK",
    "AI automation consultant US",
    "AI automation consultant UK",
    "workflow diagnostic",
    "content automation",
    "reporting automation",
    "product data automation",
    "product data cleanup automation",
    "catalog image QA automation",
    "review intelligence automation",
    "content fact checking automation",
    "market monitoring automation",
    "internal workflow automation",
  ],
}
