const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://www.smartcoretech.co.uk").replace(/\/$/, "")

export const siteConfig = {
  name: "SmartCore Technologies Ltd",
  shortName: "SmartCore Technologies",
  url: siteUrl,
  title: "AI Workflow Automation Consulting | SmartCore",
  description:
    "SmartCore maps repetitive operational work and builds controlled AI workflows for feedback, product data, content, reporting, and internal decisions.",
  email: "partnerships@smartcoretech.co.uk",
  address: {
    streetAddress: "Office 15055, 182-184 High Street North",
    addressLocality: "East Ham",
    addressRegion: "London",
    postalCode: "E6 2JA",
    addressCountry: "GB",
  },
  keywords: [
    "AI automation consulting",
    "AI workflow automation",
    "AI workflow automation consulting",
    "operational workflow automation",
    "operational intelligence",
    "process intelligence",
    "workflow diagnostics",
    "strategic advisory",
    "systems delivery",
    "workflow automation",
    "AI-enabled systems",
    "business process automation",
    "workflow diagnostic",
    "content automation",
    "reporting automation",
    "product data automation",
    "product data cleanup automation",
    "catalog image QA automation",
    "review intelligence automation",
    "content fact checking automation",
    "market monitoring automation",
    "internal workflow automation",
  ],
}
